version: '3'

services:
  newfdborg:
    image: $IMAGE:stage
    container_name: newfdborg
    restart: always
    expose:
      - "3000"
    environment:
      VIRTUAL_HOST: $VIRTUAL_HOST
      LETSENCRYPT_HOST: $LETSENCRYPT_HOST
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL

networks:
  default:
    external:
      name: frontend_default
